### ISSUE TITLE
import('python').find_installation('python3').get_install_dir() adds an extra 'local' to the path

### ISSUE THREAD

**Issue by jameswestman** [mesonbuild/meson#10459]
**Describe the bug**
Meson is installing my Python project to the wrong location. Specifically, `import('python').find_installation('python3').get_install_dir()` is returning a wrong location with an extra 'local' path segment.

**To Reproduce**
meson.build:
```meson
project('meson_bug',
          version: '0.1.0',
)

message(import('python').find_installation('python3').get_install_dir())
```

No other files are necessary to demonstrate the bug. Just run `meson _build`. The `message()` line prints `Message: /usr/local/local/lib/python3.10/site-packages/`.

**Expected behavior**
The `message` line should print something like `/usr/local/lib/python3.10/site-packages/`.

**system parameters**
* Fedora 36
* Python 3.10.4
* Meson 0.62.1
* Ninja 1.10.2

**Comment by tristan957** [comment]
@eli-schwartz @xclaesse the issue here seems to be that the prefix is defaulting to `/usr/local` and the `purelib` and `platlib` install paths seem to be `/local/...`, so the paths get appended as `/usr/local/local/...`. It isn't clear if the purelib and platlib paths are right to me.

On Ubuntu 18:

```
$ python3 -c "import sysconfig; print(sysconfig.get_paths(vars={'base': '', 'platbase': '', 'installed_base': ''}))"
{'stdlib': '/lib/python3.6', 'platstdlib': '/lib/python3.6', 'purelib': '/lib/python3.6/site-packages', 'platlib': '/lib/python3.6/site-packages', 'include': '/include/python3.6m', 'platinclude': '/usr/include/python3.6m', 'scripts': '/bin', 'data': '.'}
```

On Fedora 36:

```
$ python3 -c "import sysconfig; print(sysconfig.get_paths(vars={'base': '', 'platbase': '', 'installed_base': ''}))"
{'stdlib': '/lib64/python3.10', 'platstdlib': '/lib64/python3.10', 'purelib': '/local/lib/python3.10/site-packages', 'platlib': '/local/lib64/python3.10/site-packages', 'include': '/include/python3.10', 'platinclude': '/usr/include/python3.10', 'scripts': '/local/bin', 'data': '/local'}
```

**Comment by eli-schwartz** [comment]
I'm going to hazard a wild guess that continued inconsistent patching by a dozen different distros has once again broken our heuristics, given it changes depending on the version of Fedora.

The emergency solution of last recourse here, is to define the option `-Dpython.install_env=prefix` (default value) to "system", which will avoid trying to fit the python installation directories into your chosen `--prefix`.


The proper solution will be to try to figure out what, exactly, we are supposed to do in a situation where Fedora is plainly trying to tell us that even when we configure with --prefix=/usr, python files should be installed into /usr/local because they want `pip install` to default to that. Yippee.

**Comment by tristan957** [comment]
I think we should bring this up with Fedora to be honest. Tried opening a discussion on bugzilla, but unsuccessful trying to create an account.

**Comment by tristan957** [comment]
@bonzini any chance you can report this on the RedHat Bugzilla? I have been trying to create an account, but have been unsuccessful.

**Comment by tristan957** [comment]
I filed this downstream at https://bugzilla.redhat.com/show_bug.cgi?id=2097183. I'll post here with any updates.

**Comment by marcusmueller** [comment]
As a datapoint, this is also on fedora36, it also fails if you specify `meson setup --prefix=/tmp/foobar` (i.e., install_sources installs to /tmp/foobar/local/lib/python3.10/site-packages/ ).

**Comment by stewartadam** [comment]
Possibly the same/similar issue on MacOS with python3 installed via brew, I see a duplicate `/opt/homebrew` prefix when using `python.get_install_dir()`:  `/opt/homebrew/opt/homebrew/lib/python3.10/site-packages/`

Expected value is ` /opt/homebrew/lib/python3.10/site-packages/`

**Comment by ret2libc** [comment]
Is there a workaround in meson we can apply in the meantime? I'm having the same problem in a project I work on.

**Comment by tristan957** [comment]
Presumably, Meson could use the `purelib` / `platlib` directly if they are absolute paths. I'll let @eli-schwartz decide if it is worth a PR.

**Comment by stewartadam** [comment]
> Is there a workaround in meson we can apply in the meantime? I'm having the same problem in a project I work on, on MacOS.

`python.install_env` defaults to `prefix`, but setting it to `auto` instead should be closer to what we want (just be aware it **does** potentially install files outside of the prefix).

Unfortunately, there's (I think) still a bug with that because instead of using the system folders for purelib/platlib, meson appears to concat `sys.prefix` with purelib/platlib, which still results in invalid paths on MacOS because purelib/platlib are absolute paths.

Using purelib/platlib directly works though.

**Comment by stewartadam** [comment]
@ret2libc my currently implemented workaround is is to avoid using `python.install_sources()` in meson.build and directly and add an option in meson_options.txt:
```
option('force_system_purelib', type : 'boolean', value : false,
       description : 'If enabled, ignores meson-detected python.get_install_dir() ' +
                     'and uses the python installation\'s purelib instead. ' +
                     'See: https://github.com/mesonbuild/meson/issues/10459#issuecomment-1376843163')
```

then in meson.build:
```
meson_purelib = python.get_install_dir()
system_purelib = python.get_path('purelib')
pylib = meson_purelib # by default

# if workaround was enabled then we ignore meson and install to the system python's purelib
python_detection_workaround = get_option('force_system_purelib')

if python_detection_workaround
  pylib = system_purelib
endif
pymoduledir = join_paths(pylib, meson.project_name())
install_subdir('mypymodule', install_dir: pymoduledir)
```

Caveat being this is fine because my module is pure python so I don't need platlib. This approach defaults to meson's values and will preserves compatibility if this gets fixed in a later release, but for now I can instruct my MacOS users to set `meson setup -Dpython_detection_workaround=true` to workaround the issue.

**Comment by hroncok** [comment]
See https://docs.fedoraproject.org/en-US/fedora/f36/release-notes/developers/Development_Python/#sect-install_scheme for Fedora.

**Comment by tristan957** [comment]
This was fixed in Fedora 37 and still works in Fedora 38. Closing since this was a Fedora issue the whole time.

**Comment by tristan957** [comment]
> Presumably, Meson could use the purelib / platlib directly if they are absolute paths. I'll let @eli-schwartz decide if it is worth a PR.

This is still a potential possibility however for future issues.

**Comment by marcusmueller** [comment]
Fine with closing it, by the way – had to migrate away from meson for this reason before F37 already, hope to revisit once development time resurfaces.

**Comment by robtaylor** [comment]
I'm getting this issue still on macosx 
With prefix set to $HOME/.local:
```
Installing crlcore/src/pyCRL/Constant.cpython-311-darwin.so to /Users/roberttaylor/.local/opt/homebrew/lib/python3.11/site-packages/coriolis
Installing crlcore/src/pyCRL/CRL.cpython-311-darwin.so to /Users/roberttaylor/.local/opt/homebrew/lib/python3.11/site-packages/
Installing /Users/roberttaylor/coriolis/crlcore/python/__init__.py to /Users/roberttaylor/.local/opt/homebrew/lib/python3.11/site-packages/coriolis
```

**Comment by tristan957** [comment]
I wonder if https://github.com/mesonbuild/meson/issues/12113 is related.

**Comment by robtaylor** [comment]
It certainly looks similar...

**Comment by joanmarie** [comment]
I'm seeing it in Ubuntu (at least in 23.10). I tried installing the following gnome modules:
* Orca (which I maintain)
* Accerciser
* Secrets

All three wind up with stuff going into `/usr/local/local`. It seems similar to the Fedora 36 issue:

```
$ python3 -c "import sysconfig; print(sysconfig.get_paths(vars={'base': '', 'platbase': '', 'installed_base': ''}))"
{'stdlib': '/lib/python3.11', 'platstdlib': '/lib/python3.11', 'purelib': '/local/lib/python3.11/dist-packages', 'platlib': '/local/lib/python3.11/dist-packages', 'include': '/include/python3.11', 'platinclude': '/usr/include/python3.11', 'scripts': '/local/bin', 'data': '/local'}
```

All other distros (so far) seem to not have this problem.

I'll look for and/or file a downstream issue.

**Comment by robtaylor** [comment]
I've already made patches and justified the solution here. Could a
maintainer please revisit?

**Comment by tristan957** [comment]
Please revisit what?

**Comment by robtaylor** [comment]
The solution and PR discussed in #12113

**Comment by tristan957** [comment]
I have asked a Homebrew maintainer to take a look at that issue.

**Comment by robtaylor** [comment]
It's kind of not a homebrew issue per se -
`python_info.py:get_install_paths` is trying to install in system library
locations, and that causes the problem.
That could be the issue on ubuntu as well.

**Comment by eli-schwartz** [comment]
> It's kind of not a homebrew issue per se -
> `python_info.py:get_install_paths` is trying to install in system library locations, and that causes the problem.


You mean because meson is a build system for system software, right?


> That could be the issue on ubuntu as well - fundamentally its a sysconfig issue.
> 
> One general work around could be to just always install to posix-prefix?


At least on Linux, that's the default...

Debian folds, mutilates, and spindles theirs via third party patching, so we special case this by checking their system library location as "deb_system".

**Comment by robtaylor** [comment]
Installing in system locations should be done by the system packaging
mechanism. sure if meson wants to grow the ability to do that, that would
make sense, but right now it can’t - hence the issues being faced.

**Comment by tristan957** [comment]
The issue being faced sounds like a broken Homebrew build.

**Comment by robtaylor** [comment]
Nope, its purely that python_info.py is choosing osx_framework_library scheme, and installing to that location isn't something that is expected behaviour - its OSX system installed libraries only.

**Comment by eli-schwartz** [comment]
> Installing in system locations should be done by the system packaging mechanism. sure if meson wants to grow the ability to do that, that would make sense, but right now it can’t - hence the issues being faced.

That's not how system packaging works.

Build systems have the ability to be configured with a --prefix option. This use case is fundamental to real build systems, and meson unconditionally supports this use case for generic language support encompassing C, C++, Fortran, Rust, Swift, Java, D, Vala, and numerous others, on top of data files, executable scripts, configuration files, and a wide range of other types of build system artifacts.

This is all 100% configurable to suit a wide range of use cases. The builtin defaults are designed for the common case.

...

Python is a special case here because python doesn't have a usability story for defining or selecting installation locations. There is work ongoing to make this better but no timeframe for solving it as far as I'm aware.

The defaults which meson selects are intended to integrate with the rest of meson's configuration schema, which for example works well with `--prefix=/usr` and `--prefix="$HOME/.local`, and on systems that patched python to look in /usr/local it works there too. It works for `--prefix=/opt/myapp` too, which is also a thing that some people do.

Due to the ever-changing and undocumented chaos that is a dozen vendors each patching python in incompatible ways, sometimes this miscalculates, and we may have to add more bizarroland hacks, but it's important to document what the expected behavior is in such cases and why the hack is correct.

Probably it was a mistake to ever trust sysconfig. It's not a standard if no one follows it.

**Comment by eli-schwartz** [comment]
If you need to override the builtin detection you can use `-Dprefix=/usr -Dpython.platlibdir=/usr/path/to/site-packages -Dpython.purelibdir=/usr/path/to/site-packages`

**Comment by robtaylor** [comment]
well, indeed, and agreed - the issue seems to me that sysconfig doesn't distinguish between locations that are system installed (i.e. part of the operating system), and places where installs should go

**Comment by robtaylor** [comment]
homebrew is at fault here as well, as sysconfig.get_preferred_scheme("prefix") shouldn't ever return a system install  (i.e. non-prefix install) location, as I raised here https://github.com/orgs/Homebrew/discussions/4858

**Comment by robtaylor** [comment]
> If you need to override the builtin detection you can use `-Dprefix=/usr -Dpython.platlibdir=/usr/path/to/site-packages -Dpython.purelibdir=/usr/path/to/site-packages`

The issue on mac is that you *always* have this issue, thanks to the above issue, and no-one at any level seems to want to fix it....

**Comment by robtaylor** [comment]
Sorry for not being clear. The issue is fundamentally the same one: deb_system isn't a prefix scheme.
I don't have access to a suitable fedora box, but likely the same issue there

```
>>> print(sysconfig._INSTALL_SCHEMES['deb_system'])
{'stdlib': '{installed_base}/lib/python{py_version_short}', 'platstdlib': '{platbase}/lib/python{py_version_short}', 'purelib': '{base}/lib/python3/dist-packages', 'platlib': '{platbase}/lib/python3/dist-packages', 'include': '{installed_base}/include/python{py_version_short}{abiflags}', 'platinclude': '{installed_platbase}/include/python{py_version_short}{abiflags}', 'scripts': '{base}/bin', 'data': '{base}'}
```

**Comment by eli-schwartz** [comment]
I'm not sure what this has to do with "deb_system isn't a prefix scheme" but as I feared, this conversation isn't looking likely to come to a conclusion about what is going on, let alone how to solve it, so I'm going to retire from the ticket for now.

**Comment by robtaylor** [comment]
if only this was actually followed by distros.. https://packaging.python.org/en/latest/specifications/externally-managed-environments/#marking-an-interpreter-as-using-an-external-package-manager

**Comment by robtaylor** [comment]
relevant PEP668 discussion: https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302/111?u=pradyunsg
@eli-schwartz I agree, this is very frustrating!

**Comment by tristan957** [comment]
The Fedora issue has been fixed for a while

**Comment by eli-schwartz** [comment]
> Ugh, no. Sorry. Ignoring the technically correct answer as suggested during discussion, victim blaming, and then threatening users for utilizing their system to acquire software that isn't available as a wheel is not acceptable and that PEP is the worst thing to happen to Python in a decade. It's almost as bad as the python 2 -> 3 migration pain points. It's only less bad because it doesn't affect Windows users.

You don't solve a technical problem by training users to add a flag to pip.conf acknowledging that they agree their concerns aren't valuable to others and they should not ask for help achieving their goals.

And with that, I'm taking a break from thinking about the woes of the python ecosystem for at least a week. Unsubscribed, do not @ me, suffer your self inflicted issues in silence for all I care, G.O.O.D.B.Y.E.

**Comment by robtaylor** [comment]
@eli-schwartz was that directed at me?.... I've certainly not intended to ignore any technicallty correct answer, victim blame or threaten users so quite confused at your response.

**Comment by tristan957** [comment]
I think Eli is just done with any python packaging issues for a bit :). Don't blame yourself! Like I said, I have reached out to my homebrew contact. I'll see what he says on Monday.

**Comment by robtaylor** [comment]
Thanks @tristan957 that's appreciated. Having spent a while on this, I totally get his frustration...

**Comment by robtaylor** [comment]
also my apologies for hijacking! I initially confused which ticket I saw the activity on.

**Comment by tristan957** [comment]
No problem. Yes, Python packaging is one of the worst aspects about it. Leaves much to be desired :(.
