### ISSUE TITLE
Can't detect C and CXX compiler icx-cl.exe on Windows

### ISSUE THREAD

**Issue by jiangjianshan** [mesonbuild/meson#14089]
Hello,
 I'm using meson 1.6.1 and my github respositry [msvc-pkg](https://github.com/jiangjianshan/msvc-pkg). I have tried to compile [spral](https://github.com/ralna/spral) using icx-cl and ifx. But build failed from the very begining. 

[spral.zip](https://github.com/user-attachments/files/18341540/spral.zip)

Following below steps can produce this issue:
```bat
git clone https://github.com/jiangjianshan/msvc-pkg.git
cd msvc-pkg
bootstrap.bat
```
unzip spral.zip into *packages* folder inside *msvc-pkg*, then run
```bat
mpt spral
```

From the file *packages/spral/build.bat*, you can see the options has been set in *meson setup*.

Here is part of error output logging:
```bat
Visual C++ Tools Version     : 14.42.34433
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.12.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
:: initializing oneAPI environment...
   Initializing Visual Studio command-line environment...
   Visual Studio version 17.12.3 environment configured.
   "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\"
   Visual Studio command-line environment initialized for: 'x64'
:  compiler -- latest
:  debugger -- latest
:  dev-utilities -- latest
:  dpl -- latest
:  mkl -- latest
:  mpi -- latest
:  ocloc -- latest
:  tbb -- latest
:: oneAPI environment initialized ::
"Cleaning spral 2024.05.08"
"Configuring spral 2024.05.08"
        1 file(s) copied.
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\mesonbuild\mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\msetup.py", line 365, in run
    app.generate()
  File "C:\Python312\Lib\site-packages\mesonbuild\msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\msetup.py", line 210, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 322, in __init__
    self.parse_project()
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 129, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1321, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1490, in add_languages
    success = self.add_languages_for(args, required, for_machine)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1533, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check, self.subproject)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\compilers\detect.py", line 109, in detect_compiler_for
    env.coredata.process_compiler_options(lang, comp, env, subproject)
  File "C:\Python312\Lib\site-packages\mesonbuild\coredata.py", line 755, in process_compiler_options
    self.add_compiler_options(comp.get_options(), lang, comp.for_machine, env, subproject)
                              ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\mesonbuild\compilers\c.py", line 555, in get_options
    raise RuntimeError('This is a transitory issue that should not happen. Please report with full backtrace.')
RuntimeError: This is a transitory issue that should not happen. Please report with full backtrace.
The Meson build system
Version: 1.6.1
Source dir: E:\Githubs\msvc-pkg\releases\spral-2024.05.08
Build dir: E:\Githubs\msvc-pkg\releases\spral-2024.05.08\build64
Build type: native build
Project name: SPRAL
Project version: 2024.05.08
Fortran compiler for the host machine: C:\Program Files (x86)\Intel\oneAPI\compiler\latest\bin\ifx.exe (intel-llvm-cl 2024.2.1)
```

I have found this issue should be caused by the bug of detect.py. 'icl' should be changed to 'icl' and 'icx-cl'. Could you check it and updated it to the newest version of meson?
![image](https://github.com/user-attachments/assets/d2355abb-0bac-4819-b990-585df61ebc17)

**Comment by dcbaker** [comment]
@jpakkane, more option refactor fallout

**Comment by dcbaker** [comment]
This looks like a regression to me, if you wanted to verify, this might work on 1.5.x, though you may need to set the `CC` and `CXX` environment variables to get the oneAPI compilers.

**Comment by jiangjianshan** [comment]
@dcbaker , I have set CC, CXX and FC these environment variable inside *packages/spral/build.bat*. This issue can be very easy to be reproduced. For my understanding, only need to update the detect.py as my previous comment.

**Comment by dcbaker** [comment]
All that line in detect.py does is list a set of default compilers we search for, while we should add the oneAPI compilers to that list (we have the older Intel compilers), the issue you're running into is more-or-less an assertion related to option handling, which was changed in the 1.6 release. Things may work fine with the oneAPI compilers in 1.5 though

**Comment by jiangjianshan** [comment]
@dabaker, thanks. Maybe I have to swtich back to 1.5.x version now until 1.6.x release has fix this issue.

**Comment by dcbaker** [comment]
If it does work with 1.5 please let me know, that would make this a regression that I would push to have resolved before 1.7 or the next 1.6 release.

**Comment by jiangjianshan** [comment]
@dcbaker , I have tried meson 1.5.2 but faced the same issue as 1.6.1.

**Comment by H0R5E** [comment]
I am using `ifx` and setting `FC=ifx` with version 1.5.2 works for me.

**Comment by jiangjianshan** [comment]
Hello, I have just tried the newest version 1.7.0, but faced the same issue as before.

**Comment by Tom-Evers** [comment]
Same issue. Setting cc/cxx to icx or icx-cl breaks meson

**Comment by Tom-Evers** [comment]
I've found the problem and created a [pull request](https://github.com/mesonbuild/meson/pull/14304)

**Comment by dcbaker** [comment]
I merged the pr, is this resolved now?

**Comment by jiangjianshan** [comment]
@Tom-Evers , @dcbaker , could you try to change to CC and CXX from clang-cl to icx-cl in this https://github.com/jiangjianshan/msvc-pkg/blob/main/packages/spral/build.bat file? Then to see whether the issue has been solved.

**Comment by cathaypacific8747** [comment]
I created a simple Fortran 90 hello world program and tested it on the following configurations:
```yml
matrix:
  os:
    - windows-latest
  toolchain:
    - { compiler: intel, version: "2025.0" } # icx, ifx
    - { compiler: intel-classic, version: "2021.12" } # icl, ifort
  python-version:
    - "3.13"
  meson-version:
    - "meson==1.4.2" # works fine
    - "meson==1.5.0" # regression introduced
    - "meson==1.5.1"
    - "meson==1.5.2"
    - "meson==1.6.0"
    - "meson==1.6.1"
    - "meson==1.7.0"
    - "https://github.com/mesonbuild/meson/archive/1412abc516e56b7d90f36fc75acb3e4b8c294e30.zip" # PR 14304
    - "git+https://github.com/mesonbuild/meson.git" # latest master branch
```
(GitHub Actions: https://github.com/cathaypacific8747/meson_bug_14089/actions/runs/13771981596)

PR https://github.com/mesonbuild/meson/pull/14304 partially fixed the regression introduced in `1.5.0`, but it reveals another exception:
```py
Traceback (most recent call last):
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\msetup.py", line 408, in run
    app.generate()
    ~~~~~~~~~~~~^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\msetup.py", line 189, in generate
    return self._generate(env, capture, vslite_ctx)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\msetup.py", line 296, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 663, in generate
    self.generate_target(t)
    ~~~~~~~~~~~~~~~~~~~~^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 1072, in generate_target
    o, s = self.generate_single_compile(target, src, False, [],
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                                        header_deps + d_generated_deps + fortran_order_deps,
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                        fortran_inc_args)
                                        ^^^^^^^^^^^^^^^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 3015, in generate_single_compile
    commands += self._generate_single_compile_target_args(target, compiler)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 2911, in _generate_single_compile_target_args
    commands = self.generate_basic_compiler_args(target, compiler)
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\backend\backends.py", line 1027, in generate_basic_compiler_args
    commands += compiler.get_option_compile_args(target, self.environment, target.subproject)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\meson_bug_14089\meson_bug_14089\.venv\Lib\site-packages\mesonbuild\compilers\c.py", line 508, in get_option_compile_args
    assert isinstance(std, str)
           ~~~~~~~~~~^^^^^^^^^^
```

Switching to the deprecated Intel Fortran Compiler Classic reveals another bug:
```py
meson.build:1:0: ERROR: Unknown compiler(s): [['icl']]
The following exception(s) were encountered:
Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
```

Complete Log: [logs_35468354251.zip](https://github.com/user-attachments/files/19168753/logs_35468354251.zip)

**Comment by moi15moi** [comment]
I dont have any problem with the version 1.8.3, so it seems to be fixed.

**Comment by abc8747** [comment]
I can confirm that intel 2025.0, python3.13 with meson==1.8.3, 1.9.0rc1, 1.9.0rc2 works:
https://github.com/abc8747/meson_bug_14089/actions/runs/17023253675
