### ISSUE TITLE
Spurious sandbox violations from name clash with subprojects dir

### ISSUE THREAD

**Issue by acfoltzer** [mesonbuild/meson#2481]
The check to determine whether a sandbox violation has occurred appears to be overly zealous: it flags as a violation any file path that contains the `subproject_dir` string, even if it's a completely unrelated directory. This breaks my project in 0.43.

I will be submitting a pull request shortly with a test case that demonstrates the problem (done: #2482).

**Comment by zajo** [comment]
I don't understand the concept of sandboxing in Meson but 0.43 *completely* breaks my build scripts, too.

**Comment by nirbheek** [comment]
@zajo in the same way as this bug or some other way?

**Comment by zajo** [comment]
Yes, sorry -- I get:

```
Meson encountered an error in file subprojects/boost_1_64_0/meson.build, line 10, column 0:
Sandbox violation: Tried to grab file error_code.cpp from a different subproject.
```

By the way, how do I use pip3 to install an older version of Meson?

**Comment by nirbheek** [comment]
You can checkout the 0.42 branch in git and run meson.py directly from the source tree.

Where is `error_code.cpp` exactly in your source tree?

**Comment by liugang** [comment]
@zajo I think this is fixed by PR #2466 if you are using wrap, but not merged now.

my main meson.build as below: 
```
project('test1', 'cpp')

subproject('boost_1_64_0')

```
and I'm using your meson.build for bootst_1_64

```
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
mkdir t1
cd t1
mkdir subprojects
tar xf ../boost_1_64_0.tar.bz2 -C subprojects/
ls subprojects/boost_1_64_0/
meson builddir
ninja -C builddir/
```

and I can build it successfully.

**Comment by liugang** [comment]
- PR #2492 fixed this issue
- PR #2466 fixed wrap-file issue

**Comment by wberrier** [comment]
I'm also getting the "Sandbox violation: Tried to grab file code.cpp from a different subproject."

In my case, I'm using:

    subproject_dir: '.'

and all my files from that subproject and failing on this error (ie: if I remove the file in question from meson.build, it fails on the next build).

Also note that PR #2492 does not fix the issue for me.

**Comment by jpakkane** [comment]
The fact that '.' is a permitted subproject dir name is a bug. #2505 fixes that by making it a hard error. What are you trying to achieve by setting that value?

**Comment by wberrier** [comment]
I would be saddened if the ability to specify "`subproject_dir: '.'`" was removed, but maybe there's a better mechanism for my situation?

The scenario:

Directory structure:

    project_dir/
        meson.build
        gitsubmodule/
            meson.build
            meson_options.txt

The gitsubmodule is shared among several parent projects, and shares `meson_options.txt` that apply to the submodule.  Before I knew I could change the subprojects dir (which, btw, I thought was brilliant to default to a consistent location of `subprojects`), I treated the submodule as a subdirectory, but then I had a bunch of verbose and redundant code for parsing options.  Turning `gitsubmodule` into a subproject really cleaned it up with meson_options.txt.

The main problem: meson is not the primary build system of this project (there are several), and I don't have control of the file structure and submodule locations.  I'm hoping one day meson will be the primary build system, but that is a long term goal and it's currently a second class citizen.

So... what are my options here?  What about when #2505 is merged?

**Comment by jpakkane** [comment]
We have thought about better ways of having shared options between many projects.  Perhaps something like:

    option('optname', ..., refer_to_top_project : true)

Which would make that option refer to the top level option if it exists but to create its own if it does not (because, for example, it is being built standalone, not subproject).

If you don't have to support Windows, then the simplest solution would probably be to add symlinks to the `subprojects` directory pointing to the actual directories. This should work (and if it does not, we probably can do the requisite changes to make it work). Alternatively you should be able to define submodules twice so they are checked out to both paths. This works if you only use one build system at a time but, granted, gets messy if you need to do two at the same time.

**Comment by wberrier** [comment]
@jpakkane thanks for the ideas.

I ended up creating a symlink from `subprojects` to `.`, which worked great.  I tend to shy away from checking in symlinks to code, but I think it's a good compromise between having a consistent subprojects dir, and not being able to move the git submodules, given this particular project doesn't have to support windows.

That being said, for older legacy projects, being very flexible as to what `subprojects` can be set to (including `.`) would be one less hurdle for adoption, particularly if Windows support was required.
