### ISSUE TITLE
LANG should not be relied on by a build tool to operate properly

### ISSUE THREAD

**Issue by imirkin** [mesonbuild/meson#2868]
It seems like the user's LANG setting is relied upon by meson. It should work independently of such user environment details. (In my personal case, I set LANG to C since I don't use a utf8-capable terminal emulator.)

Ideally the solution isn't "switch to a different terminal emulator in order to be able to build projects with meson". Specifically in addition to a ton of error spew while trying to build mesa, it ends up failing in one of the build steps (which naturally succeeds with an autoconf-based build in the same environment). I haven't investigated in detail why that failure happens, could be something mesa-specific. The larger point stands even if it is though.

My guess is that this is due to some implicit conversions between bytes and runes. These should all have explicit encodings set, probably configured in the build file and defaulting to utf8. When printing messages to the screen, a conversion with errors=ignore would be fine.

**Comment by jpakkane** [comment]
> Specifically in addition to a ton of error spew while trying to build mesa

This has been fixed recently to only print the issues if the files you process are not plain ASCII and the encoding is not utf-8.

> These should all have explicit encodings set, probably configured in the build file and defaulting to utf8.

This is what it should already do. If it does not then it's a bug. If you can isolate an error case with details let us know and we'll get it fixed. Patches are also welcome.

**Comment by imirkin** [comment]
I'm going to recheck, but I suspect there will still be issues -- the mesa C files are not plain ascii - they have copyright symbols, and probably random utf8-style quotes, author names with accents, etc. And should such a C file be printed to the console, I'd understand that LANG=C would prevent some of those from appearing properly -- I wouldn't mind. But for building, doesn't seem to matter.

Anyways, I'll figure out how to check the latest meson code. I thought that this issue was being disregarded and hence filed a bug here. Didn't occur to me to check first with latest tree. My bad.

**Comment by jpakkane** [comment]
> But for building, doesn't seem to matter.

We don't look inside C files so it does not matter. The warning text is for cases where people generate config files with `configure_file` and other such things that need to parse contents of files.

**Comment by imirkin** [comment]
Good news! With the latest meson checkout, the "your console doesn't support utf8" errors are all indeed gone. However I still have the error which I originally had with the mesa build, which feels like it's related to the LANG=C thing (since it goes away with LANG=en_US.utf8):

```
xmlpool_options_h = custom_target(
  'xmlpool_options.h',
  input : ['gen_xmlpool.py', 't_options.h'],
  output : 'options.h',
  command : [prog_python2, '@INPUT@', meson.current_source_dir()],
  capture : true,
  depend_files : files('ca.po', 'es.po', 'de.po', 'nl.po', 'sv.po', 'fr.po'),
)
```
Which results in
```
[16/872] Generating xmlpool_options.h with a meson_exe.py custom command.
FAILED: src/util/xmlpool/options.h 
/usr/lib/python-exec/python3.4/python3 /home/ilia/src/meson/meson.py --internal exe /home/ilia/src/mesa/build/meson-private/meson_exe_python2_3a2775749d7d46cabc2a5a7f5c3d828a49a86fac.dat
Traceback (most recent call last):
  File "/home/ilia/src/meson/meson.py", line 26, in <module>
    sys.exit(main())
  File "/home/ilia/src/meson/meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/home/ilia/src/meson/mesonbuild/mesonmain.py", line 325, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/ilia/src/meson/mesonbuild/mesonmain.py", line 279, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/ilia/src/meson/mesonbuild/scripts/meson_exe.py", line 76, in run
    return run_exe(exe)
  File "/home/ilia/src/meson/mesonbuild/scripts/meson_exe.py", line 62, in run_exe
    output.write(stdout)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12955-12957: ordinal not in range(128)
```
Note that the script does work with the autoconf build, so I don't think the error is in the script itself.

**Comment by imirkin** [comment]
Aha, looks like command produces some non-ascii output. This fixes it, although I'm not sure if that's the right solution. Ultimately popen should be invoked in binary mode, and everything should just be passed through.

```
diff --git a/mesonbuild/scripts/meson_exe.py b/mesonbuild/scripts/meson_exe.py
index 643e1af7..570d177f 100644
--- a/mesonbuild/scripts/meson_exe.py
+++ b/mesonbuild/scripts/meson_exe.py
@@ -15,6 +15,7 @@
 import os
 import sys
 import argparse
+import locale
 import pickle
 import platform
 
@@ -58,8 +59,8 @@ def run_exe(exe):
                              child_env['PATH'])
     p, stdout, stderr = Popen_safe(cmd + exe.cmd_args, env=child_env, cwd=exe.workdir)
     if exe.capture and p.returncode == 0:
-        with open(exe.capture, 'w') as output:
-            output.write(stdout)
+        with open(exe.capture, 'wb') as output:
+            output.write(stdout.encode(locale.getpreferredencoding(False), errors='replace'))
     if stderr:
         sys.stderr.write(stderr)
     return p.returncode
```

**Comment by dcbaker** [comment]
actually, autotools doesn't use that script, scons does. Autotools open codes it in a makefile. JYFI

**Comment by imirkin** [comment]
Either way, a script which generates utf8 chars (or random binary noise) to stdout shouldn't bring down a build when the user's terminal can't display those chars properly.

I think just making popen return a binary thing would solve these issues, and imho be the right thing to do. I've been avoiding learning py3 stuff so far though, so I don't know how that'd be done here. I also see that Popen_safe includes universal_newlines=True, so that would probably have to be accounted for somewhere, somehow.

**Comment by dcbaker** [comment]
fair enough

**Comment by imirkin** [comment]
Any suggestions from the meson masters?

Should I mail out the patch from the comment above? (As it does make the mesa build succeed for me.) Or is a deeper dive into meson necessary where all the inter-process comm is fixed to deal in bytes rather than strings?

**Comment by jpakkane** [comment]
The script in question is not a part of Meson core, it is just a wrapper for setting the environment when running external programs as part of the build. The patch above is the way to get it fixed, but instead of importing locale and encoding the output, the fix should use plain `Popen` rather than `popen_safe`, read the `stdout` in bytes and write it out as bytes without ever touching its contents.

This does require manually encoding the stderr printing below because AFAICR `sys.stderr` only takes strings, not bytes.

And now that I look at the code, it really should print `stdout` if capture is not set. Now it just swallows it silently...

**Comment by imirkin** [comment]
Yes, I understand that the script in question is not part of meson. I was trying to address the more generic problem of "program executed by build tool should be allowed to spew random garbage and not have build tool die of encoding errors".

Yeah, script output was being swallowed - I'm insufficiently familiar with meson to know what the proper/expected flow is. I assumed it was being saved to a buffer to be printed later optionally (e.g. if the program were to exit with an error).

I'll try to have a look at the capture thing and understand more of the work flow over the weekend if I get some time.

**Comment by jpakkane** [comment]
>program executed by build tool should be allowed to spew random garbage and not have build tool die of encoding errors

Definitely. We have had a few bugs on this but they should mostly be fixed by now. If you find new cases, repor them and we'll get them fixed.

> I'll try to have a look at the capture thing and understand more of the work flow over the weekend if I get some time.

Great, thanks.

**Comment by imirkin** [comment]
> Definitely. We have had a few bugs on this but they should mostly be fixed by now. If you find new cases, repor them and we'll get them fixed.

We must not be understanding each other. This bug report is precisely this situation. Some script in the mesa build generates some junk to stdout (that is not ASCII), meson crashes. As it happens, it's valid utf8, but not valid ascii, and my LANG=C. This could also happen with LANG=en_US.utf8 since not all binary sequences are valid utf8 sequences.

**Comment by imirkin** [comment]
Oh, I see what capture means. It means "run the script and capture its output to $file". OK, that makes sense then. Definitely want nothing to do with Popen_safe there.
