### ISSUE TITLE
meson 0.48.0 quietly introduces dependency on setuptools package

### ISSUE THREAD

**Issue by decathorpe** [mesonbuild/meson#4267]
The official stance is (or used to be?) that meson isn't allowed to depend on anything outside the python standard library: http://mesonbuild.com/Use-of-Python.html#dependency-hell

These commits introduce a run-time dependency on setuptools, because it adds imports from `pkg_resources`:

https://github.com/mesonbuild/meson/commit/2ee28029f945d74d01e63d6efd8802c9df03b28f
https://github.com/mesonbuild/meson/commit/86298f2109d215ad6b26d3462af7b685d52d0dd7

Probably the documentation on mesonbuild.com needs to be updated, and a mention of the new dependency in the release notes for 0.48.0 would have been nice.

**Comment by decathorpe** [comment]
I'm on fedora, where setuptools is not part of a minimal buildroot, and this caused initial issues when meson was updated to 0.48.0 (it was fixed by @ignatenkobrain already, by adding setuptools to runtime dependencies of meson).

I was just surprised by the quietly added dependency, since I assumed the "nothing except stdlib" thing was still valid.

I understand the reasoning for adding the setuptools requirement - I'd just have liked it to be documented in the release notes at least, since a new dependency is noteworthy in my opinion. And updating the documentation needs to be updated to state "nothing except stdlib and setuptools".

**Comment by hroncok** [comment]
Note that python3 in Fedora 29+ recommends python3-setuptools, so most *users* won't be affected by this as they will get setuptools anyway. On the other hand Fedora's build system does not install recommended dependencies and hence other Fedora packages failed to use meson at build time.

**Comment by lazka** [comment]
I wrote a distutils command once which only uses setuptools on Windows as a build dep: https://github.com/quodlibet/quodlibet/blob/605c54c3270db46f9e1532e3f50a3ee349176f0d/quodlibet/gdist/launchers.py

A bit extreme, but that gets your dependencies to a minimum.

**Comment by jpakkane** [comment]
The Debian packaging [has had a fix applied for this for a while now](https://tracker.debian.org/news/989630/accepted-meson-0480-2-source-into-unstable/).

**Comment by decathorpe** [comment]
(Just cleaning up after myself, since this is obviously going nowhere.)

**Comment by PaulBone** [comment]
This is still broken:

```
paul@fluorine /tmp $ pip3 install --user meson
Collecting meson
  Downloading https://files.pythonhosted.org/packages/b6/22/55d0b08695abf2f425e7b4130b37f6202ca5e37c93dca7512f2ee2b8f4f4/meson-0.49.0.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 476kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xp36iz9y/meson/

```

The bug reported here says that the dependency on setuptools is legitamite, that's fine.  My problem is that the meson package should tell pip that it needs setuptools so that users don't see this error.  If that's not possible then the install information on the website needs to point this out.

**Comment by hroncok** [comment]
Out of curiosity. How do you have pip without setuptools?

**Comment by Tachi107** [comment]
> The Debian packaging [has had a fix applied for this for a while now](https://tracker.debian.org/news/989630/accepted-meson-0480-2-source-into-unstable/).

This doesn't seem accurate, as on a Debian 11 system `import('python').find_installation()` fails with `ERROR: <PythonExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python or it is missing setuptools`, and meson-log.txt reveals `ModuleNotFoundError: No module named 'distutils.core'`, when package `python3-distutils` is not installed.

I'm going to also report this on [bugs.debian.org](https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=meson)

**Comment by eli-schwartz** [comment]
@Tachi107 distutils is part of the stdlib and is this formally exempt from meson's policy of only depending on the stdlib.

The fact that debian incomprehensibly takes one source tree (CPython), builds it, installs it, and then chops it up into several pieces and includes a bunch of pieces of the stdlib in split subpackages, is not an indictment on meson.

distutils is a required part of the stdlib, debian is broken, meson works around this by still requiring the stdlib, but warning you if you don't have a valid python.

The error message is, admittedly, bogus nonsense. To be exact, it's a hilarious typo because it's supposed to say "or  it is missing distutils".

This is also fixed in 34ac77d6199f0fd1143018a78067c6152bf8fac7.

Anyway, be that as it may it has literally zero to do with this ticket. Even if the nonsense error message lied and said it does have to do with this ticket. Sorry for that. meson 0.60 will, again, be less confusing.

**Comment by Tachi107** [comment]
@eli-schwartz

> distutils is part of the stdlib and is thus formally exempt from meson's policy of only depending on the stdlib.

I have no doubts about that, I was just pointing out that in Debian the issue is not solved (as opposed to what @jpakkane thought), but I properly reported it on Debian's bug tracker.

> Anyway, be that as it may it has literally zero to do with this ticket. Even if the nonsense error message lied and said it does have to do with this ticket. Sorry for that. meson 0.60 will, again, be less confusing.

Yep I know that the error message mentions setuptools while it uses distutils, in fact I said that the issue appears when python3-distutils is not installed, but thanks for fixing that :)

**Comment by eli-schwartz** [comment]
The bug which jpakkane linked to is about Debian depending on python3-pkg_resources so that the entry point script /usr/bin/meson (which imports pkg_resources in order to execute `pkg_resources.load_entry_point()`) can be run without tracebacks for anything at all, including `meson --help`.

This occurred because setuptools itself happens to implement entry points like that for any package which it builds, independently of what the project itself uses. But not always, it depends on how you build the package -- e.g. current versions of setuptools attempt to use the >=3.8 stdlib `importlib.metadata.distribution` first, and if you use pip to install the wheel, I believe pip itself implements entry points by directly importing mesonbuild.mesonmain.main().

Conveniently, it is actually impossible to depend on pkg_resources since that doesn't install its own .dist-info so you cannot add it to install_requires even if you want to...

...

Anyway, once again this is two completely different and entirely unrelated issues, and the bug jpakkane linked to is what this github ticket was opened about and is indeed fixed since September 2018.

**Comment by Tachi107** [comment]
> Anyway, once again this is two completely different and entirely unrelated issues, and the bug jpakkane linked to is what this github ticket was opened about and is indeed fixed since September 2018.

Oh, you're right :/

I was reading through a bunch of bug reports on my phone and my brain decided that it was time to report an issue in the wrong place... Sorry :)

**Comment by eli-schwartz** [comment]
Eh, no big deal, happens to all of us. :)
