### ISSUE TITLE
Enabling `b_coverage` on Dlang projects throws an AttributeError

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5669]
Got an attribute error from one of my example project templets. 

Part of the error message from my travis report before I removed `b_coverage` from the build scripts.

```console 
AttributeError: 'DmdDCompiler' object has no attribute 'get_coverage_link_args'
The command "meson setup build_dir && ninja -j8 -C build_dir" exited with 2.
0.01s$ ninja -j8 -C build_dir test -v
ninja: Entering directory `build_dir'
ninja: error: loading 'build.ninja': No such file or directory
The command "ninja -j8 -C build_dir test -v" exited with 1.
```

**Comment by Cogitri** [comment]
Is there something I can help with to get coverage on D w/ meson? CC @dcbaker

**Comment by dcbaker** [comment]
It looks like for gdc we just need to move a few things around in our abstractions (I've done this already). ldc and gdc do things a bit differently, we can successfully generate their coverage data, but we don't put it anyplace useful and we don't have any tools to process them. It would be really useful to have a tool like gcovr that cold process the list files.

**Comment by Cogitri** [comment]
Hm, I guess I don't really know how coverage works w/ meson, but with dub I'd just run the coverage task, it'd generate the .lst files and I can pass those to services like codecov, so I don't see why meson would need to convert them? Also, some IDEs integrate with the .lst files already, e.g. code-d (a D plugin for VSCode) displays the coverage in the editor if it detects these .lst files

**Comment by dcbaker** [comment]
Meson general uses gcov/lcov and then uses the tools around those to generate reports. We'd need some sort of tool we can call to generate useful reports out of the .list files, and we'd need to inject some arguments so that the .lst files get put where we want them. I did get gcov support for gdc in master, so that should work now.

**Comment by Cogitri** [comment]
> We'd need some sort of tool we can call to generate useful reports out of the .list files,

I'm still not sure how the .list files aren't useful reports - e.g. Codecov can display them just fine

> and we'd need to inject some arguments so that the .lst files get put where we want them

I'll look into that, thanks

**Comment by Cogitri** [comment]
So I just asked the D folks, apparently we'll either have to run the compiled executable in the dir where we want the coverage files to end up or we have to add a custom D module (so a D source file) which sets these things when doing coverage builds (which probably is a bit fragile). There's no command line switch for DMD or LDC2 for this.

**Comment by dcbaker** [comment]
The docs seem to suggest you can control where the output goes by setting environment variables or command line arguments to the compiled test executables:
https://dlang.org/articles/code_coverage.html §Controlling the Coverage Analyser

I  guess we can just give the .lst files, but that's going to deviate from what meson generally does for coverage, so we'll need to document that.

**Comment by Cogitri** [comment]
> The docs seem to suggest you can control where the output goes by setting environment variables or command line arguments to the compiled test executables:

Oh huh, how did I not find that. Thanks :)

I guess I can give this a look if you haven't already
