### ISSUE TITLE
Expose a PEP 517 backend

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson#7863]
Python packaging is shifting away from setuptools as the only real build backend option. [PEP 517](https://www.python.org/dev/peps/pep-0517/) introduces a standard interface to insteract with build backends, [PEP 518](https://www.python.org/dev/peps/pep-0518/) introduces a standard way to specify which backend the project uses.

I think it would be interesting to see if meson could expose a Python build system backend, so that it could be used in Python packaging.

Would this be something you might consider?

**Comment by jpakkane** [comment]
I have not looked at the details, but in theory yes.

**Comment by dcbaker** [comment]
Id like to do it. The one trick is that we'd probably need a toml parser, which isn't in the standard library (yet).

**Comment by lazka** [comment]
There is https://gitlab.com/thiblahute/mesonpep517

**Comment by FFY00** [comment]
> Id like to do it. The one trick is that we'd probably need a toml parser, which isn't in the standard library (yet).

Great, I would also like to help out.

The toml parser would be the easy part, we can pull `toml` as an optional dependency.

PEP 517 mandates two hooks, `build_sdist` and `build_wheel`.

`build_sdist` build a source distribution. There isn't a standard for this yet, so we essentially just have to produce a tarball with the source code, which is pretty easy.

`build_wheel` is the one that requires work. It builds a Python wheel file, which is described in [PEP 427](https://www.python.org/dev/peps/pep-0427/).

A quick overview, a Python wheel is a zip file and its contents look something like this:
```
python_module1
python_module2
my_package.dist-info
my_package.data
```

`my_package.dist-info` is the metadata directory and `my_package.data` the data directory. The data directory can contain headers, scripts and general data, each in its own subdirectory.

Before starting working on this, everyone should read the whole PEP.

> There is [gitlab.com/thiblahute/mesonpep517](https://gitlab.com/thiblahute/mesonpep517)

I am aware, but it does not give me much confidence.

![mesonpep517-releases](https://user-images.githubusercontent.com/11718923/96369084-d34c1780-114f-11eb-8711-b613b95b157c.png)

**Comment by lazka** [comment]
> I am aware, but it does not give me much confidence.

Why is that?

**Comment by FFY00** [comment]
> Why is that?

Did you see the picture I attached? That does not seem like a reasonable release model, IMO.

The author is also inactive, at least in the recent months. Here's an issue I'd really like to see addressed.
https://gitlab.com/thiblahute/mesonpep517/-/issues/2

It also uses an unmaintained toml parser library, among other things...

I have considered using it in [one of the projects I maintain](https://github.com/libratbag/piper), but given the userbase of my project I am really not confident at all to do it.

**Comment by tp-m** [comment]
cc @thiblahute

**Comment by thiblahute** [comment]
@FFY00 Well I released often in my early testing process as it made the process simpler..  I do not think that means anything in how good the code/approach is or isn't.... 

I didn't remove intreehook requirement as it doesn't cause any issue for me and thus I do not have enough incentive to move away from it until now... patches are very much welcome!

I think we could/should move mesonpep517 in the meson three at some point but having it external also does the job . Now not reusing that work in the process for the reasons you invoke here doesn't make much sense to me :)

**Comment by dcbaker** [comment]
I can't remember which one, but I read somewhere the Brett Cannon had one of the toml modules in mind to recommend for core after toml hits 1.0. I think it would be worth figuring out where upstream is leaning and using that one

**Comment by FFY00** [comment]
> @FFY00 Well I released often in my early testing process as it made the process simpler.. I do not think that means anything in how good the code/approach is or isn't....

Sure, but I'd user alpha, beta or pre-releases in those cases. The version numbering also struck me a very odd.
 
> I didn't remove intreehook requirement as it doesn't cause any issue for me and thus I do not have enough incentive to move away from it until now... patches are very much welcome!

Great :grin: Glad to know you are not inactive and you indeed looked at the issue.

> I think we could/should move mesonpep517 in the meson three at some point but having it external also does the job . Now not reusing that work in the process for the reasons you invoke here doesn't make much sense to me :)

Yeah, I think we could use `mesonpep517` in the process.

> I can't remember which one, but I read somewhere the Brett Cannon had one of the toml modules in mind to recommend for core after toml hits 1.0. I think it would be worth figuring out where upstream is leaning and using that one

There are essentially two toml parsers, `toml` and `pytoml`. `pytoml` has been deprecated in favor of `toml`. Some projects still use `pytoml` but `toml` is definitely the recomended one. You can have a look at PyPA projects, you will see that's what they are using.

If anything makes into the standard library it will very likely be `toml`. And I am pretty sure this is the toml parser Brett was refeering to.

**Comment by thiblahute** [comment]
> > @FFY00 Well I released often in my early testing process as it made the process simpler.. I do not think that means anything in how good the code/approach is or isn't....
> 
> Sure, but I'd user alpha, beta or pre-releases in those cases. The version numbering also struck me a very odd.

Well, it is semantically correct, but yes it is the result of development cycles rather than really releasing.

I now ported `mesonpep517` to `toml` and `backend-path`, it was totally trivial.

**Comment by FRidh** [comment]
Related issue https://github.com/mesonbuild/meson/issues/7695.

**Comment by FFY00** [comment]
FYI, I have started working on this.

**Comment by thiblahute** [comment]
> FYI, I have started working on this.

You know https://gitlab.com/thiblahute/mesonpep517 is pretty active and implements most of the spec and related ones too? Scipy is in the process of moving to using it. What are you working on? I think we should move mesonpep517 to the mesonbuild org on github I wonder what is wrong with just making it official for you.

**Comment by eli-schwartz** [comment]
Some thoughts on what this would probably entail:

- meson is a general purpose, multi-language build system, building python distributions should be implemented accessible to `meson install` for multi-language projects otherwise there is no advantage of adding a pep517 backend rather than delegating to mesonpep517
  - #7251
- we can probably build off of #9110 to classify what goes into a wheel, possibly including data that isn't actual .py files or extensions automatically classified for python but nevertheless tied to the wheel. `DESTDIR=wheel-staging-tempdir/ meson install --tags python-runtime` and collect the results
  - mesonpep517 should make use of this immediately, cc @thiblahute
- an MVP should let meson build itself using meson, and install itself using meson too -- all without any dependencies. This is useful since currently bootstrapping an OS with meson in the bootstrap set includes building python, performing the setuptools/appdirs/packaging/pyparsing/more-itertools/ordered-set bootstrap dance, and with the pending deprecation of `python setup.py install` will also involve bootstrapping python-build and python-installer (or alternatively pip), as a ring0 distribution layer. Replacing that with `./meson.py setup . builddir && ninja -C builddir/ install` would be incredibly useful and offers a compelling argument to low-level OS components that meson should be pulled into the bootstrap set.

> Id like to do it. The one trick is that we'd probably need a toml parser, which isn't in the standard library (yet).

- the toml situation has gotten worse over time, not better. https://discuss.python.org/t/adopting-recommending-a-toml-parser/4068 is now on its third toml parsing library since both the previous ones have been abandoned, and there is no longer a consensus that CPython even wants to include one in the stdlib
- [PEP 621](https://www.python.org/dev/peps/pep-0621/) is accepted and finalized. We probably want to be a good ecosystem citizen and respect this, which would also save us the cost of adding a meson API to do the same thing.

**Comment by FFY00** [comment]
> You know gitlab.com/thiblahute/mesonpep517 is pretty active and implements most of the spec and related ones too? Scipy is in the process of moving to using it. What are you working on? I think we should move mesonpep517 to the mesonbuild org on github I wonder what is wrong with just making it official for you.

mesonpep517 makes several decisions I am not comfortable with, the main one being introspecting `intro-installed.json` which does not provide any context on files. My reasoning for wanting the python build backend in meson itself is so that we can develop it side by side as meson is not really designed to be used the way mesonpep517 is using it.
Currently, mesonpep517 is resorting to fragile heuristics like looking at file extensions to figure out if the binary distributions are supposed to be pure or not (https://gitlab.com/thiblahute/mesonpep517/-/blob/master/mesonpep517/buildapi.py#L407), which demonstrates the interface issue. We could fix this in meson by making it export more useful information about the installed files, but relying on this interaction makes progress slow and the development harder, as it does not only creates a gap between the development team but it also restricts us to only be able to use interfaces meson is comfortable making public.

Overall, I think mesonpep517 is a great PoC but not suitable for production use. We can, of course, improve it, but I think getting it to the state I would be comfortable using it on big projects would be much easier if the development was tightly integrated with meson itself.
Anyway, as I said in the PR, this is not my call, the meson maintainers will have to decide on it.

**Comment by xclaesse** [comment]
> Currently, mesonpep517 is resorting to fragile heuristics like looking at file extensions to figure out if the binary distributions are supposed to be pure or not

I'm not sure about the whole story here, but it feels like something we can fix by using install tags: https://github.com/mesonbuild/meson/pull/9110

**Comment by thiblahute** [comment]
> meson is not really designed to be used the way mesonpep517 is using it

I do not see why you would say that, it has been developed making sure to provide introspection data so building tools based on it was easy. This is exactly that power that we are leveraging here.

> Currently, mesonpep517 is resorting to fragile heuristics like looking at file extensions to figure out if the binary distributions are supposed to be pure or not (https://gitlab.com/thiblahute/mesonpep517/-/blob/master/mesonpep517/buildapi.py#L407), which demonstrates the interface issue

That only demonstrates that I used a quick solution when implementing because something was missing at that point. This is not the case anymore and we can now use `intro-targets.json`  determine that in a cleaner way.

---

In any case, you are welcome to reuse anything you want from mesonpep517 I made sure to use the same license as meson itself because of that. I agree integrating that component in meson could make it somehow simpler (though I have no proof of that at this point).

I also think that for this particular component avoiding external dependencies doesn't make sense at all as the main advantage of implementing pep517 is that projects built with meson can very easily leverage the Python package ecosystem (not saying for the rest of meson, but for that particular component).

**Comment by xclaesse** [comment]
> I also think that for this particular component avoiding external dependencies doesn't make sense at all as the main advantage of implementing pep517 is that projects built with meson can very easily leverage the Python package ecosystem (not saying for the rest of meson, but for that particular component).

I personally wouldn't be shocked if some methods in the python module requires external python module, especially for something as specific as this. IMHO as long as the core of meson rely only on the stdlib we should be good. But I don't know if other Meson dev share that opinion.

**Comment by tristan957** [comment]
As someone who has worked with and on mesonpep517, I definitely feel that moving into at least the mesonbuild org here on GitHub is a step in the right direction. mesonpep517 is also super far along down the pep517 spec and starting to get pep621 support. I am not sure I see advantage in merging mesonpep517 into meson proper except the ability to use internal APIs. @FFY00 maybe you could shed some light on why you think this behavior needs to exist in Meson? I definitely would hate to schism here if something could be resolved.

**Comment by nanonyme** [comment]
I would in fact suggest working on bootstrapping story here. Examples
* flit bootstrapping goes flit-core->tomli+toml-w->flit
* poetry bootstrapping goes poetry-core->poetry
Neither of these two cases require setuptools nor the soon (3.12) to be removed distutils. From that point of view if this project grew native PEP517 support, it might make sense to have it be a subproject or another project semantically so that it could be used as the primary build system for *meson*.

**Comment by eli-schwartz** [comment]
As I said above:

> an MVP should let meson build itself using meson, and install itself using meson too -- all without any dependencies

That is, officially supporting pep517 in meson should mean that meson can achieve the same goals in installing python software, EITHER by building a wheel and letting pip or python-installer install that wheel, OR by running `ninja install`. Both should produce the same files, including the dist-info, so `ninja install` would install a proper python package and not just copy over some .py files.

**Comment by FFY00** [comment]
> That is, officially supporting pep517 in meson should mean that meson can achieve the same goals in installing python software, EITHER by building a wheel and letting pip or python-installer install that wheel, OR by running `ninja install`. Both should produce the same files, including the dist-info, so `ninja install` would install a proper python package and not just copy over some .py files.

I just wanted to point out that Meson being able to bootstrap itself doesn't actually have to depend on it having a public backend, it can use a private in-tree backend that only implements the necessary to generate distributions for itself.

That said, I do think it having a public backend would make sense. But, as you point out, there are some challenges, and the decision is not up to me. I am just waiting to see what you decide.

**Comment by thiblahute** [comment]
> I just wanted to point out that Meson being able to bootstrap itself doesn't actually have to depend on it having a public backend, it can use a private in-tree backend that only implements the necessary to generate distributions for itself.

We can use an external backend implementation, I am planning on writing a meson patch to use `mesonpep517`.

**Comment by nanonyme** [comment]
Just clarifying: meson can't bootstrap itself right now, right? Since there's no meson.build so it can't build itself.

**Comment by eli-schwartz** [comment]
> We can use an external backend implementation, I am planning on writing a meson patch to use `mesonpep517`.

It currently does use an external backend called "setuptools". If we are going to move backends I'd like the move to represent a growth in functionality, not a reduction.

For example, with setuptools, meson can be installed using a "legacy" route as `python setup.py install`, mesonpep517 does of course require pep517. And in general the entire bootstrap setup of python modules on Linux distros is not (yet) prepared for pep517, but is very well prepared for setuptools.

Also, setuptools is actually a very good python build backend, both with and without pep517. :)

So I see no reason to give up setuptools unless we can actually solve the bootstrap problem once and for all, completely, 100%.

> I just wanted to point out that Meson being able to bootstrap itself doesn't actually have to depend on it having a public backend, it can use a private in-tree backend that only implements the necessary to generate distributions for itself.

Bootstrapping does NOT mean "generate distributions". It means "install distributions". Otherwise it is not bootstrapping, it is just... generating stuff which your actual bootstrap chain needs to process, but only after the full bootstrap chain has run.

This is why neither flit nor poetry are bootstrappable, but setuptools is (and while it does vendor its own dependencies for convenience, its dependencies traditionally use stdlib `distutils` rather than `setuptools` to build, for precisely this reason).

**Comment by FFY00** [comment]
> It currently does use an external backend called "setuptools". If we are going to move backends I'd like the move to represent a growth in functionality, not a reduction.
>
> For example, with setuptools, meson can be installed using a "legacy" route as python setup.py install, mesonpep517 does of course require pep517. And in general the entire bootstrap setup of python modules on Linux distros is not (yet) prepared for pep517, but is very well prepared for setuptools.
>
> Also, setuptools is actually a very good python build backend, both with and without pep517. :)
>
> So I see no reason to give up setuptools unless we can actually solve the bootstrap problem once and for all, completely, 100%.

I don't really follow your point here, it would grow functionality. By using a backend like `mesonpep517`, Meson would be able to bootstrap itself -- you could run Meson from source to install itself.

**Comment by nanonyme** [comment]
@eli-schwartz this is inaccurate. I wrote a PoC wheel installer with no external dependencies which cannot handle dependencies etc and was perfectly able to bootstrap fully functional flit using it. It was not super-hard, biggest issue is having some thing that generates entrypoints. Yes, setuptools can be bootstrapped without pep517 by directly invoking setup.py. But the chains are so complex that wheel problems supporting pep517 itself due to cyclic dependencies.

**Comment by FFY00** [comment]
FWIW, I have been working on https://github.com/FFY00/mesonpy, which deals properly with project shared libraries that are required by the Python module. It also packages executables (as wheel scripts) and has a fairly decent test coverage.

Only Linux is currently tested, but I will be working on fixing and validating support for Windows and MacOS soon.

**Comment by nanonyme** [comment]
No, flit_core does not need all those things you mentioned. The pep517 backend everyone is using is flit_core. A command-line frontend various people are using for development is flit. It takes two-step bootstrap from Python to have fully functional wheel installing system with flit_core. You can trust me on this, I have implemented it for a meta-distro.

**Comment by eli-schwartz** [comment]
The backend requires a frontend.

Flit (not core) is indeed an alternative frontend to `build`, but...

... that introduces its own dependencies in addition to flit_core, namely: docutils, requests, urllib3, idna, charset_normalizer, and of course all those use setuptools+wheel which means you still need the `build` frontend.

**Comment by eli-schwartz** [comment]
> It is absolutely awesome to be self-bootstrappable.

Self-bootstrappable is indeed awesome, but "it only requires 2 dependencies" is not "self", and I'm still not clear on what frontend you use to invoke flit_core.

**Comment by nanonyme** [comment]
> > It is absolutely awesome to be self-bootstrappable.
> 
> Self-bootstrappable is indeed awesome, but "it only requires 2 dependencies" is not "self", and I'm still not clear on what frontend you use to invoke flit_core.

I meant self-bootstrappable as being able to install Meson using Meson from source root or some other simple bootstrapping mechanism.

**Comment by nanonyme** [comment]
There is no frontend other than `python3 -flit_core.wheel` needed for a distro when pep517 backend is known to be flit_core, really. After that you get a wheel you can unpack either directly or by using the recent pypa/installer.

**Comment by eli-schwartz** [comment]
> There is no frontend other than `python3 -flit_core.wheel` needed

Oh huh, TIL. Last I checked, flit_core didn't actually provide a CLI. Now it does. That's actually pretty neat.

https://github.com/eli-schwartz/meson/commit/83a2e6692c6c2b75c532048cc7c230beb43194ea is still the long-term direction I'd like to go in, though.

**Comment by nanonyme** [comment]
Yeah, things have been changing a lot during last half a year or so. We will most likely gradually see pep517, packaging etc switch to flit_core now that bootstrapping chain exists.

**Comment by mattip** [comment]
I think this can be closed? `mesonpy` as a backend works.

**Comment by rgommers** [comment]
I believe that (a) `meson-python` is not going to be merged as a whole into this repo and (b) @eli-schwartz has plans to eventually include a PEP 517 backend directly into `meson` which may take lessons from `meson-python` (but have zero dependencies and fewer bells and whistles).

Probably good to close this issue indeed.

**Comment by nanonyme** [comment]
Is there a second issue about that venture by @eli-schwartz ? It would be good to link from here so people can follow up if it ends up being furthered or abandoned.
